env:
  browser: true
  es2021: true
  jest: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - react-hooks

settings:
  react:
    version: detect

rules: {
  "react-hooks/rules-of-hooks": error,
  "react-hooks/exhaustive-deps": warn,
  "react/prop-types": 0
}

